In [41]:
#

In [43]:
import pandas as pd

In [45]:
df_nf = pd.read_csv("data/nifty50.csv")
df_bnf = pd.read_csv("data/banknifty.csv")
df_vix = pd.read_csv("data/indiavix.csv")
df_fts = pd.read_csv("data/starter_features.csv")

In [47]:
display(df_nf.head())
display(df_bnf.head())
display(df_vix.head())
display(df_fts.head())

,date,Adj Close,Close,High,Low,Open,Volume
0,2022-01-03,17625.699219,17625.699219,17646.650391,17383.300781,17387.150391,200500
1,2022-01-04,17805.250000,17805.250000,17827.599609,17593.550781,17681.400391,247400
2,2022-01-05,17925.250000,17925.250000,17944.699219,17748.849609,17820.099609,251500
3,2022-01-06,17745.900391,17745.900391,17797.949219,17655.550781,17768.500000,236500
4,2022-01-07,17812.699219,17812.699219,17905.000000,17704.550781,17797.599609,239300

,date,Adj Close,Close,High,Low,Open,Volume
0,2022-01-03,36421.476562,36421.898438,36492.101562,35526.601562,35585.199219,219000
1,2022-01-04,36839.718750,36840.148438,36887.800781,36374.398438,36551.250000,190500
2,2022-01-05,37695.460938,37695.898438,37862.398438,36756.351562,36943.550781,237400
3,2022-01-06,37489.812500,37490.250000,37752.500000,37058.449219,37242.550781,199000
4,2022-01-07,37739.164062,37739.601562,38134.851562,37427.800781,37667.050781,183300

         date  Adj Close      Close       High        Low       Open  Volume
0  2022-01-03  16.450001  16.450001  16.809999  15.450000  16.219999       0
1  2022-01-04  16.120001  16.120001  16.680000  15.710000  16.450001       0
2  2022-01-05  17.230000  17.230000  17.379999  15.090000  16.120001       0
3  2022-01-06  17.980000  17.980000  18.420000  16.400000  17.230000       0
4  2022-01-07  17.600000  17.600000  18.090000  16.860001  17.980000       0

,date,ret_1d,ret_5d,ret_10d,ret_20d,ret_intraday,ret_overnight,high_low_range,log_volume,volume_ratio_20d,...,vix_level,vix_change,vix_5d_change,vix_ma_ratio,close_vs_252d_high,close_vs_252d_low,dow,ret_zscore,ma5_smooth_signal,volume_normalized
0,2022-01-03,NaN,NaN,NaN,NaN,0.013720,NaN,0.014941,12.208570,NaN,...,16.450001,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0.180301
1,2022-01-04,0.010187,NaN,NaN,NaN,0.007005,0.003160,0.013145,12.418762,NaN,...,16.120001,-0.020061,NaN,NaN,NaN,NaN,1,1.144972,NaN,0.228022
2,2022-01-05,0.006740,NaN,NaN,NaN,0.005901,0.000834,0.010926,12.435198,NaN,...,17.230000,0.068858,NaN,NaN,NaN,NaN,2,0.740212,0.008001,0.232194
3,2022-01-06,-0.010005,NaN,NaN,NaN,-0.001272,-0.008745,0.008024,12.373703,NaN,...,17.980000,0.043529,NaN,NaN,NaN,NaN,3,-1.225885,-0.006304,0.216931
4,2022-01-07,0.003764,NaN,NaN,NaN,0.000848,0.002913,0.011253,12.385473,NaN,...,17.600000,-0.021135,NaN,NaN,NaN,NaN,4,0.390858,-0.005354,0.219780

In [49]:
display(df_nf.info())
display(df_bnf.info())
display(df_vix.info())
display(df_fts.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 988 entries, 0 to 987
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       988 non-null    object
 1   Adj Close  988 non-null    float64
 2   Close      988 non-null    float64
 3   High       988 non-null    float64
 4   Low        988 non-null    float64
 5   Open       988 non-null    float64
 6   Volume     988 non-null    int64
dtypes: float64(5), int64(1), object(1)
memory usage: 54.2+ KB

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 987 entries, 0 to 986
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       987 non-null    object
 1   Adj Close  987 non-null    float64
 2   Close      987 non-null    float64
 3   High       987 non-null    float64
 4   Low        987 non-null    float64
 5   Open       987 non-null    float64
 6   Volume     987 non-null    int64
dtypes: float64(5), int64(1), object(1)
memory usage: 54.1+ KB

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 983 entries, 0 to 982
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       983 non-null    object
 1   Adj Close  983 non-null    float64
 2   Close      983 non-null    float64
 3   High       983 non-null    float64
 4   Low        983 non-null    float64
 5   Open       983 non-null    float64
 6   Volume     983 non-null    int64
dtypes: float64(5), int64(1), object(1)
memory usage: 53.9+ KB

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 988 entries, 0 to 987
Data columns (total 32 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   date                988 non-null    object
 1   ret_1d              987 non-null    float64
 2   ret_5d              983 non-null    float64
 3   ret_10d             978 non-null    float64
 4   ret_20d             968 non-null    float64
 5   ret_intraday        988 non-null    float64
 6   ret_overnight       987 non-null    float64
 7   high_low_range      988 non-null    float64
 8   log_volume          980 non-null    float64
 9   volume_ratio_20d    847 non-null    float64
 10  close_vs_ma5        984 non-null    float64
 11  close_vs_ma20       969 non-null    float64
 12  close_vs_ma50       939 non-null    float64
 13  momentum_5_20       968 non-null    float64
 14  vol_5d              983 non-null    float64
 15  vol_20d             968 non-null    float64
 16  vol_50d             938 non-null    float64
 17  rsi_14              974 non-null    float64
 18  bn_ret_1d           987 non-null    float64
 19  bn_ret_5d           983 non-null    float64
 20  nifty_bn_spread     987 non-null    float64
 21  nifty_bn_corr_20d   968 non-null    float64
 22  vix_level           988 non-null    float64
 23  vix_change          987 non-null    float64
 24  vix_5d_change       983 non-null    float64
 25  vix_ma_ratio        969 non-null    float64
 26  close_vs_252d_high  737 non-null    float64
 27  close_vs_252d_low   737 non-null    float64
 28  dow                 988 non-null    int64
 29  ret_zscore          987 non-null    float64
 30  ma5_smooth_signal   984 non-null    float64
 31  volume_normalized   980 non-null    float64
dtypes: float64(30), int64(1), object(1)
memory usage: 247.1+ KB

None

In [51]:
# Conversion to pandas dataframe for uniformity

df_nf["date"] = pd.to_datetime(df_nf["date"])
df_bnf["date"] = pd.to_datetime(df_bnf["date"])
df_vix["date"] = pd.to_datetime(df_vix["date"])
df_fts["date"] = pd.to_datetime(df_fts["date"])

In [53]:
# renaming duplicate columns so that they dont coincide/conflict after merging

df_nf = df_nf.add_prefix("nf_")
df_bnf = df_bnf.add_prefix("bnf_")
df_vix = df_vix.add_prefix("vix_")


# keeping date same for all dataframes

df_nf.rename(columns={"nf_date": "date"}, inplace=True)
df_bnf.rename(columns={"bnf_date": "date"}, inplace=True)
df_vix.rename(columns={"vix_date": "date"}, inplace=True)

# all columns are now uniquely named

In [56]:
# merging the dataset
##### merged on dates; how='inner' => intersection of dates, only common dates among the dataframes survive

df_master = (
    df_nf
    .merge(df_bnf, on="date", how="inner")
    .merge(df_vix, on="date", how="inner")
    .merge(df_fts, on="date", how="inner")
)

In [58]:
display(df_master.shape)
display(df_master.head())
display(df_master.info())

(983, 50)

,date,nf_Adj Close,nf_Close,nf_High,nf_Low,nf_Open,nf_Volume,bnf_Adj Close,bnf_Close,bnf_High,...,vix_level,vix_change,vix_5d_change,vix_ma_ratio,close_vs_252d_high,close_vs_252d_low,dow,ret_zscore,ma5_smooth_signal,volume_normalized
0,2022-01-03,17625.699219,17625.699219,17646.650391,17383.300781,17387.150391,200500,36421.476562,36421.898438,36492.101562,...,16.450001,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0.180301
1,2022-01-04,17805.250000,17805.250000,17827.599609,17593.550781,17681.400391,247400,36839.718750,36840.148438,36887.800781,...,16.120001,-0.020061,NaN,NaN,NaN,NaN,1,1.144972,NaN,0.228022
2,2022-01-05,17925.250000,17925.250000,17944.699219,17748.849609,17820.099609,251500,37695.460938,37695.898438,37862.398438,...,17.230000,0.068858,NaN,NaN,NaN,NaN,2,0.740212,0.008001,0.232194
3,2022-01-06,17745.900391,17745.900391,17797.949219,17655.550781,17768.500000,236500,37489.812500,37490.250000,37752.500000,...,17.980000,0.043529,NaN,NaN,NaN,NaN,3,-1.225885,-0.006304,0.216931
4,2022-01-07,17812.699219,17812.699219,17905.000000,17704.550781,17797.599609,239300,37739.164062,37739.601562,38134.851562,...,17.600000,-0.021135,NaN,NaN,NaN,NaN,4,0.390858,-0.005354,0.219780

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 983 entries, 0 to 982
Data columns (total 50 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   date                983 non-null    datetime64[ns]
 1   nf_Adj Close        983 non-null    float64
 2   nf_Close            983 non-null    float64
 3   nf_High             983 non-null    float64
 4   nf_Low              983 non-null    float64
 5   nf_Open             983 non-null    float64
 6   nf_Volume           983 non-null    int64
 7   bnf_Adj Close       983 non-null    float64
 8   bnf_Close           983 non-null    float64
 9   bnf_High            983 non-null    float64
 10  bnf_Low             983 non-null    float64
 11  bnf_Open            983 non-null    float64
 12  bnf_Volume          983 non-null    int64
 13  vix_Adj Close       983 non-null    float64
 14  vix_Close           983 non-null    float64
 15  vix_High            983 non-null    float64
 16  vix_Low             983 non-null    float64
 17  vix_Open            983 non-null    float64
 18  vix_Volume          983 non-null    int64
 19  ret_1d              982 non-null    float64
 20  ret_5d              978 non-null    float64
 21  ret_10d             973 non-null    float64
 22  ret_20d             963 non-null    float64
 23  ret_intraday        983 non-null    float64
 24  ret_overnight       982 non-null    float64
 25  high_low_range      983 non-null    float64
 26  log_volume          976 non-null    float64
 27  volume_ratio_20d    843 non-null    float64
 28  close_vs_ma5        979 non-null    float64
 29  close_vs_ma20       964 non-null    float64
 30  close_vs_ma50       934 non-null    float64
 31  momentum_5_20       963 non-null    float64
 32  vol_5d              978 non-null    float64
 33  vol_20d             963 non-null    float64
 34  vol_50d             933 non-null    float64
 35  rsi_14              969 non-null    float64
 36  bn_ret_1d           982 non-null    float64
 37  bn_ret_5d           978 non-null    float64
 38  nifty_bn_spread     982 non-null    float64
 39  nifty_bn_corr_20d   963 non-null    float64
 40  vix_level           983 non-null    float64
 41  vix_change          982 non-null    float64
 42  vix_5d_change       978 non-null    float64
 43  vix_ma_ratio        964 non-null    float64
 44  close_vs_252d_high  733 non-null    float64
 45  close_vs_252d_low   733 non-null    float64
 46  dow                 983 non-null    int64
 47  ret_zscore          982 non-null    float64
 48  ma5_smooth_signal   979 non-null    float64
 49  volume_normalized   976 non-null    float64
dtypes: datetime64[ns](1), float64(45), int64(4)
memory usage: 384.1 KB

None

In [60]:
df_master.to_csv("master_dataframe.csv", index=False)

In [69]:
df_master.columns.

Index(['date', 'nf_Adj Close', 'nf_Close', 'nf_High', 'nf_Low', 'nf_Open',
       'nf_Volume', 'bnf_Adj Close', 'bnf_Close', 'bnf_High', 'bnf_Low',
       'bnf_Open', 'bnf_Volume', 'vix_Adj Close', 'vix_Close', 'vix_High',
       'vix_Low', 'vix_Open', 'vix_Volume', 'ret_1d', 'ret_5d', 'ret_10d',
       'ret_20d', 'ret_intraday', 'ret_overnight', 'high_low_range',
       'log_volume', 'volume_ratio_20d', 'close_vs_ma5', 'close_vs_ma20',
       'close_vs_ma50', 'momentum_5_20', 'vol_5d', 'vol_20d', 'vol_50d',
       'rsi_14', 'bn_ret_1d', 'bn_ret_5d', 'nifty_bn_spread',
       'nifty_bn_corr_20d', 'vix_level', 'vix_change', 'vix_5d_change',
       'vix_ma_ratio', 'close_vs_252d_high', 'close_vs_252d_low', 'dow',
       'ret_zscore', 'ma5_smooth_signal', 'volume_normalized'],
      dtype='object')